#!/bin/bash

SRC=src
OUT=out
ESBUILD=node_modules/.bin/esbuild
TACHYONS=node_modules/tachyons/css/tachyons.min.css

rm -rf $OUT
mkdir -p $OUT

$ESBUILD $SRC/index.js --bundle --minify --sourcemap --outfile=$OUT/index.bundle.js

cp index.html $OUT/index.html
cp $TACHYONS $OUT/
cp kanjikai.css $OUT/

convert -size 128x128 -gravity center -background '#2F1758' -fill white \
    -font /System/Library/Fonts/ヒラギノ丸ゴ\ ProN\ W4.ttc label:解 \
    $OUT/favicon.temp.png
convert $OUT/favicon.temp.png -size 32x32 $OUT/favicon.png
rm $OUT/favicon.temp.png
